spring.datasource.url=jdbc:postgresql://ep-curly-dew-aqkwze83-pooler.c-8.us-east-1.aws.neon.tech/hermes_db?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

# Esto lee directamente las variables de Render, y si no existen, usa los valores por defecto
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_BPx0Z2KGEeon}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.mail.host=://gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración obligatoria para el puerto dinámico de Render
server.port=${PORT:8080}
